# Generated by Django 4.0.6 on 2022-07-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='userId',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name=100),
        ),
    ]
