# Generated by Django 4.1 on 2022-08-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0002_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
