# Generated by Django 4.0.6 on 2022-07-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0002_rename_author_comment_userid_alter_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='genre_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='danceapp.genre'),
        ),
    ]
