# Generated by Django 4.0.6 on 2022-07-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0003_genre_alter_post_updatedate_post_genre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='genre_name',
            new_name='genreName',
        ),
    ]
