# Generated by Django 4.0.6 on 2022-08-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
