# Generated by Django 4.0.6 on 2022-08-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0005_post_likes_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_username',
        ),
    ]
