# Generated by Django 4.0.6 on 2022-07-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0005_post_like_count_post_likes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_count',
            new_name='likes_count',
        ),
    ]
