# Generated by Django 4.0.6 on 2022-07-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0006_rename_like_count_post_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
