# Generated by Django 4.0.6 on 2022-08-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0007_likepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
