# Generated by Django 4.1 on 2022-08-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0008_delete_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
