# Generated by Django 4.0.6 on 2022-08-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0012_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
