# Generated by Django 4.1 on 2022-08-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0013_course_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseTime',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
