# Generated by Django 4.1 on 2022-08-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0014_course_coursetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
